### PR TITLE
Concept map fix

### LINKED ISSUE #237: Fix concept map bubbles and edges

### PR DESCRIPTION
**Pull request by aadiraju**
## Description
Fixes the concept map by making it more consistent, and adds drag functionality to the map as well for smaller displays that need it

## Types of changes
What types of changes does your code introduce?
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (only improve the code quality no change in functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] Issue has been created
- [ ] Every file touched is linted
- [ ] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue
closes #237 

## Tests
Please describe in detail what tests you added or changed.

## Screenshots (if appropriate):
image

### CODE REVIEW

File: src/app/course/concept-map/concept-map.component.ts [hunk 1]
```diff
@@ -16,6 +16,8 @@ export class ConceptMapComponent implements OnInit {
     conceptMapGraph: ConceptMapGraph;
 
     @Input() currCourse: Course;
+    scrolling: { x: number, y: number };
```
Comment (keyvankhademi) [inline src/app/course/concept-map/concept-map.component.ts:19]: Please remove these lines

Comment (aadiraju) [reply src/app/course/concept-map/concept-map.component.ts]: Done

**Review by keyvankhademi — APPROVED** [review]
