### PR TITLE
Fix Linting

### LINKED ISSUE #321: Fix Linting Warnings

### PR DESCRIPTION
**Pull request by carson-ricca**
## Description
- Fix linting warnings in the code.

## Types of changes
What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (only improve the code quality no change in functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] Issue has been created
- [x] Every file touched is linted
- [x] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue
- Closes #321
 
## Tests
- N/A

### CODE REVIEW

File: src/app/problems/json-editor/json-editor.component.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export class JsonEditorComponent implements OnInit {
     // TODO - Determine the Proper Typing.
     editor: any;
```
Comment (carson-ricca) [inline src/app/problems/json-editor/json-editor.component.ts:14]: This can be left I believe as Mat was working on removing the schemas.

File: src/polyfills.ts [hunk 2]
```diff
@@ -65,4 +65,5 @@ import 'zone.js/dist/zone';  // Included with Angular CLI.
 /***************************************************************************************************
  * APPLICATION IMPORTS
  */
+// eslint-disable-next-line @typescript-eslint/no-explicit-any
```
Comment (carson-ricca) [inline src/polyfills.ts:68]: Disabled this one as it was related to Angular CLI and nothing we implemented.

**Review by keyvankhademi — APPROVED** [review]
