### PR TITLE
Fixes ESLint issues for course

### LINKED ISSUE #125: Fix ESLint issues for the Course section

### PR DESCRIPTION
**Pull request by aadiraju**
closes #125

### CODE REVIEW

File: src/app/components/course/course-registration/course-register.component.ts [hunk 1]
```diff
@@ -7,10 +7,10 @@ import {MessageService} from '@app/_services/message.service';
 import {CourseRegistrationResponse, REGISTRATION_STATUS, MESSAGE_TYPES} from '@app/_models';
 
 const STEPPER_STAGES = {
-    ENTER_NAME: 0,
-    CONFIRM_IDENTITY: 1,
-    VERIFICATION: 2,
-    REGISTERED: 3,
+    enterName: 0,
```
Comment (keyvankhademi) [inline src/app/components/course/course-registration/course-register.component.ts:10]: This was correct to be PascalCase I'll modify the eslint. Please pull from master and change this back.

Comment (keyvankhademi) [reply src/app/components/course/course-registration/course-register.component.ts:10]: UPPER_CASE*

**Review by keyvankhademi — APPROVED** [review]
