### PR TITLE
Fix FAQ page

### LINKED ISSUE #90: FAQ page breaks in deployment

### PR DESCRIPTION
**Pull request by Opeyem1a**
+ refactored classes/ids in FAQ component
+ small UI improvements
+ confirmed proper data flow

Closes #90

### CODE REVIEW

File: src/app/components/faq/faq.component.ts [hunk 1]
```diff
@@ -1,24 +1,27 @@
...
-    .subscribe((faqs) => {
-      this.faqs = faqs;
-    });
-  }
+    ngOnInit(): void {
+        this.faqService
+            .getFaqs()
+            .subscribe((faqs) => {
+                this.faqs = faqs;
+                this.emptyObservable = !faqs.length;
```
Comment (keyvankhademi) [inline src/app/components/faq/faq.component.ts:23]: You really don't need this i think. You can check If(faqs) or if(faqs.length) anywhere you need this.

Comment (Opeyem1a) [reply src/app/components/faq/faq.component.ts:23]: aye aye

**Review by keyvankhademi — APPROVED** [review]
