### PR TITLE
Problem create edit form fixes

### LINKED ISSUE #218: Fix styling for problem edit/create

### PR DESCRIPTION
**Pull request by aadiraju**
## Description
Edits styling of problem forms to make it clearer.

## Types of changes
What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (only improve the code quality no change in functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] Issue has been created
- [x] Every file touched is linted
- [ ] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue
closes #218 

## Tests
Please describe in detail what tests you added or changed.

### CODE REVIEW

File: src/app/problems/json-editor/json-editor.component.ts [hunk 1]
```diff
@@ -21,7 +21,8 @@ export class JsonEditorComponent implements OnInit {
 
     ngOnInit(): void {
         const element = document.getElementById('editor');
-
+        //change ID to make sure each editor is separated
+        element.id = 'editor-' + Math.floor(Math.random() * 1000);
```
Comment (keyvankhademi) [inline src/app/problems/json-editor/json-editor.component.ts:25]: Why do we need this?
Also having random is not a good idea. It's better to have a deterministic solution.

**Review by keyvankhademi — APPROVED** [review]
