### PR TITLE
Course Edit Bug Fix

### LINKED ISSUE #223: Question Edit not Working Properly

### PR DESCRIPTION
**Pull request by carson-ricca**
## Description
- Fixes bug with changing courses on a question.
- Refactors functionality of setCourse and event.
- Updates tests.

## Types of changes
What types of changes does your code introduce?
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (only improve the code quality no change in functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] Issue has been created
- [x] Every file touched is linted
- [x] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue
- Closes #223 

## Tests
- Updates required tests.

### CODE REVIEW

File: src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts [hunk 1]
```diff
@@ -47,16 +47,18 @@ export class JavaEditSnippetComponent implements OnInit {
     }
 
     ngOnInit(): void {
-        if (this.questionDetails.event) {
+        // TODO: refactor => typeof this.questionDetails.event === 'number'
```
Comment (carson-ricca) [inline src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts:50]: Could not determine a good way to refactor this `if` statement. Seems like a larger issue with the model that is out of the scope of the bug-fix.

File: src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts [hunk 2]
```diff
@@ -55,28 +56,47 @@ export class JavaCreateSnippetComponent implements OnInit {
...
 
     /**
-     * Select a course from the given event.
-     * @param value - The event.
+     * Select a course from the given DOM event.
+     * @param value - The DOM event.
      */
-    courseSelectedEvent(value: Event): void {
-        this.courseSelectedById(+(value.target as HTMLInputElement).value);
+    courseSelectionChanged(value: Event): void {
```
Comment (keyvankhademi) [inline src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts:62]: Are you sure about the type `Event` here?

Comment (carson-ricca) [reply src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts:62]: Yeah. I could just pass the value directly to the other functions instead in the `(change)` instead of passing a DOM event?

File: src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts (hunk 1 above)
Comment (keyvankhademi) [reply src/app/problems/problem-edit/java-edit-snippet/java-edit-snippet.component.ts:50]: Yes!

File: src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts (hunk 2 above)
Comment (keyvankhademi) [reply src/app/problems/problem-create/java-create-snippet/java-create-snippet.component.ts:62]: Let's keep it this way! I'm not sure which is better tho.

**Review by keyvankhademi — APPROVED** [review]
